name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: "Tag of the version to rollback to (e.g., v1.2.3)"
        required: true
      environment:
        description: "Environment to rollback (dev, uat, prod)"
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod

jobs:
  rollback:
    name: Rollback to ${{ github.event.inputs.version_tag }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version_tag }}
          token: ${{ secrets.GIT_HUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17

      # Set dev variables
      - name: Set Dev Env Vars
        if: ${{ github.event.inputs.environment == 'dev' }}
        run: |
          echo "client_id=${{ secrets.DEV_CONNECTED_APP_CLIENT_ID }}" >> $GITHUB_ENV
          echo "client_secret=${{ secrets.DEV_CONNECTED_APP_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "cloudhub_env=${{ vars.DEV_CLOUDHUBENVIRONMENT }}" >> $GITHUB_ENV
          echo "target=${{ vars.DEV_TARGET }}" >> $GITHUB_ENV
          echo "env_name=${{ vars.DEV_ENV }}" >> $GITHUB_ENV
          echo "key=${{ vars.DEV_KEY }}" >> $GITHUB_ENV

      # Set UAT variables
      - name: Set UAT Env Vars
        if: ${{ github.event.inputs.environment == 'uat' }}
        run: |
          echo "client_id=${{ secrets.UAT_CONNECTED_APP_CLIENT_ID }}" >> $GITHUB_ENV
          echo "client_secret=${{ secrets.UAT_CONNECTED_APP_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "cloudhub_env=${{ vars.UAT_CLOUDHUBENVIRONMENT }}" >> $GITHUB_ENV
          echo "target=${{ vars.UAT_TARGET }}" >> $GITHUB_ENV
          echo "env_name=${{ vars.UAT_ENV }}" >> $GITHUB_ENV
          echo "key=${{ vars.UAT_KEY }}" >> $GITHUB_ENV

      # Set PROD variables
      - name: Set PROD Env Vars
        if: ${{ github.event.inputs.environment == 'prod' }}
        run: |
          echo "client_id=${{ secrets.PROD_CONNECTED_APP_CLIENT_ID }}" >> $GITHUB_ENV
          echo "client_secret=${{ secrets.PROD_CONNECTED_APP_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "cloudhub_env=${{ vars.PROD_CLOUDHUBENVIRONMENT }}" >> $GITHUB_ENV
          echo "target=${{ vars.PROD_TARGET }}" >> $GITHUB_ENV
          echo "env_name=${{ vars.PROD_ENV }}" >> $GITHUB_ENV
          echo "key=${{ vars.PROD_KEY }}" >> $GITHUB_ENV

      - name: Validate Required Variables
        run: |
          if [[ -z "$target" || -z "$client_id" || -z "$client_secret" || -z "$cloudhub_env" || -z "$env_name" || -z "$key" ]]; then
            echo "❌ One or more required environment values are missing!"
            echo "target=$target"
            echo "client_id=$client_id"
            echo "client_secret=${#client_secret}"
            echo "cloudhub_env=$cloudhub_env"
            echo "env_name=$env_name"
            echo "key=${#key}"
            exit 1
          fi

      - name: Deploy Rollback Version
        run: |
          mvn clean deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
            -Dclient.id="$client_id" \
            -Dclient.secret="$client_secret" \
            -DcloudhubEnvironment="$cloudhub_env" \
            -Dtarget="$target" \
            -Denv="$env_name" \
            -Dkey="$key"
