name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: "Tag of the version to rollback to (e.g., v1.2.3)"
        required: true
      environment:
        description: "Environment to rollback (dev, uat, prod)"
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod

jobs:
  rollback:
    name: Rollback to ${{ github.event.inputs.version_tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version_tag }}
          token: ${{ secrets.GIT_HUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17

      - name: Rollback to ${{ github.event.inputs.version_tag }}
        run: |
          mvn clean deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
            -Dclient.id="${{ secrets[format('{0}_CONNECTED_APP_CLIENT_ID', github.event.inputs.environment.toUpper())] }}" \
            -Dclient.secret="${{ secrets[format('{0}_CONNECTED_APP_CLIENT_SECRET', github.event.inputs.environment.toUpper())] }}" \
            -DcloudhubEnvironment="${{ vars[format('{0}_CLOUDHUBENVIRONMENT', github.event.inputs.environment.toUpper())] }}" \
            -Dtarget="${{ vars[format('{0}_TARGET', github.event.inputs.environment.toUpper())] }}" \
            -Denv="${{ vars[format('{0}_ENV', github.event.inputs.environment.toUpper())] }}" \
            -Dkey="${{ vars[format('{0}_KEY', github.event.inputs.environment.toUpper())] }}"
