name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: "Tag of the version to rollback to (e.g., v1.2.3)"
        required: true
      environment:
        description: "Environment to rollback (dev, uat, prod)"
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod

jobs:
  rollback:
    name: Rollback to ${{ github.event.inputs.version_tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version_tag }}
          token: ${{ secrets.GIT_HUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17

      - name: Rollback to ${{ github.event.inputs.version_tag }}
        env:
          ENV: ${{ github.event.inputs.environment }}
          CLIENT_ID: ${{ secrets.DEV_CONNECTED_APP_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DEV_CONNECTED_APP_CLIENT_SECRET }}
          CLOUDHUB_ENV: ${{ vars.DEV_CLOUDHUBENVIRONMENT }}
          TARGET: ${{ vars.DEV_TARGET }}
          ENV_NAME: ${{ vars.DEV_ENV }}
          KEY: ${{ vars.DEV_KEY }}
        run: |
          if [[ "$ENV" == "uat" ]]; then
            CLIENT_ID="${{ secrets.UAT_CONNECTED_APP_CLIENT_ID }}"
            CLIENT_SECRET="${{ secrets.UAT_CONNECTED_APP_CLIENT_SECRET }}"
            CLOUDHUB_ENV="${{ vars.UAT_CLOUDHUBENVIRONMENT }}"
            TARGET="${{ vars.UAT_TARGET }}"
            ENV_NAME="${{ vars.UAT_ENV }}"
            KEY="${{ vars.UAT_KEY }}"
          elif [[ "$ENV" == "prod" ]]; then
            CLIENT_ID="${{ secrets.PROD_CONNECTED_APP_CLIENT_ID }}"
            CLIENT_SECRET="${{ secrets.PROD_CONNECTED_APP_CLIENT_SECRET }}"
            CLOUDHUB_ENV="${{ vars.PROD_CLOUDHUBENVIRONMENT }}"
            TARGET="${{ vars.PROD_TARGET }}"
            ENV_NAME="${{ vars.PROD_ENV }}"
            KEY="${{ vars.PROD_KEY }}"
          fi

          mvn clean deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
            -Dclient.id="$CLIENT_ID" \
            -Dclient.secret="$CLIENT_SECRET" \
            -DcloudhubEnvironment="$CLOUDHUB_ENV" \
            -Dtarget="$TARGET" \
            -Denv="$ENV_NAME" \
            -Dkey="$KEY"
